# Generated by Django 4.1.5 on 2023-01-21 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('role', models.TextField(choices=[('SOLO', 'Solo'), ('ROCKER', 'Rocker'), ('NETRUNNER', 'Netrunner'), ('MEDIA', 'Media'), ('NOMAD', 'Nomad'), ('FIXER', 'Fixer'), ('COP', 'Cop'), ('CORP', 'Corp'), ('TECHIE', 'Techie'), ('MEDTECHIE', 'Medtechie')], default='SOLO')),
                ('picture', models.ImageField(max_length=200, upload_to='pictures_storage/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
