# Generated by Django 4.1.5 on 2023-01-21 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cp2020', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('role', models.TextField(choices=[('SOLO', 'Solo'), ('ROCKER', 'Rocker'), ('NETRUNNER', 'Netrunner'), ('MEDIA', 'Media'), ('NOMAD', 'Nomad'), ('FIXER', 'Fixer'), ('COP', 'Cop'), ('CORP', 'Corp'), ('TECHIE', 'Techie'), ('MEDTECHIE', 'Medtechie')], default='SOLO')),
                ('picture', models.ImageField(max_length=200, upload_to='pictures_storage/')),
                ('stat_REF', models.DecimalField(decimal_places=0, max_digits=2)),
                ('stat_TECH', models.DecimalField(decimal_places=0, max_digits=2)),
                ('stat_INT', models.DecimalField(decimal_places=0, max_digits=2)),
                ('stat_COOL', models.DecimalField(decimal_places=0, max_digits=2)),
                ('stat_LUCK', models.DecimalField(decimal_places=0, max_digits=2)),
                ('stat_MA', models.DecimalField(decimal_places=0, max_digits=2)),
                ('stat_BODY', models.DecimalField(decimal_places=0, max_digits=2)),
                ('stat_EMP', models.DecimalField(decimal_places=0, max_digits=2)),
                ('stat_ATTR', models.DecimalField(decimal_places=0, max_digits=2)),
                ('MA_Run', models.DecimalField(decimal_places=0, max_digits=3)),
                ('MA_Leap', models.DecimalField(decimal_places=0, max_digits=3)),
                ('MA_Lift', models.DecimalField(decimal_places=0, max_digits=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CharacterDetails',
        ),
    ]
