# Generated by Django 4.1.5 on 2023-01-27 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cp2020', '0005_characterdetail_int_accounting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
