# Generated by Django 4.1.5 on 2023-01-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp2020', '0006_alter_characterdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterdetail',
            name='stat_ATTR',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='characterdetail',
            name='stat_BODY',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='characterdetail',
            name='stat_COOL',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='characterdetail',
            name='stat_EMP',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='characterdetail',
            name='stat_INT',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='characterdetail',
            name='stat_LUCK',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='characterdetail',
            name='stat_MA',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='characterdetail',
            name='stat_REF',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='characterdetail',
            name='stat_TECH',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
