# Generated by Django 4.1.5 on 2023-02-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp2020', '0010_alter_characterdetail_stat_attr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterdetail',
            name='BODY_BTM',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='characterdetail',
            name='BODY_Save_Nr',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='characterdetail',
            name='EMP_Humanity',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
    ]
